### ISSUE TITLE
Task: Write a readme based on discussion on Element

### ISSUE THREAD

**Issue by kevingzhang** [tearust/teaproject#2]
I also created a new public repo https://github.com/tearust/teaproject  This repo will be our public oriented portal. it has wiki, discussion board. 
It is a supplementary of our website. 
We can leave our website as a static HTML page while put most interactive parts to this github repo. 
We can frequently update and invite community member to discuss on this board
while has wiki for detail explanation than website
I would ask 
geopor to take the main responsibility of this repo.
geopor: please try to get more users get to know and start to discuss on this repo
Many projects use Discord, but I would prefer to have github instead of Discord. 
It may generate more activities in github and improve our github rating in the future.
Currently some of the works are done in the moderators repo which is not correct. they should be done in the new teaproject repo

**Comment by kevingzhang** [comment]
Please also consider how to use the wiki, and discussion board. how to introduce traffic from our website, make new links in our website.

**Comment by geopor** [comment]
Edited.

@kevingzhang can you confirm the following format will work for **tea-docs/config.yaml** sidebar:

```
  - name: Links
    path: Links/README.md
    children:
      - name: Github Discussions
         path: https://github.com/tearust/teaproject/discussions
      - name: Github Wiki
         path: https://github.com/tearust/teaproject/wiki
```
